strictness: medium
test-warnings: true
doc-warnings: true
member-warnings: true
inherits:
  - default
  - full_pep8
ignore-paths:
  - docs/
  - ci/
  - example_videos/
  - maps/
  - scenarios/
  - tutorials
autodetect: false
max-line-length: 120

pycodestyle:
  run: true

pydocstyle:
  disable:
    - D104 # Missing docstring in public package
    - D203 # 1 blank line required before class docstring (Conflict with D211)
    - D205 # 1 blank line required between summary line and description
    - D212 # Multi-line docstring summary should start at the first line (Conflict with 213)
    - D407 # Missing dashed underline after section
    - D415 # First line should end with a period, question mark, or exclamation point

pyflakes:
  run: true

mccabe:
  run: true

pylint:
  disable:
    - import-error
    - too-many-arguments
    - too-many-locals
    - missing-module-docstring
    - subprocess-popen-preexec-fn

mypy:
  run: true
